# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ec51d8d9f7beac80e6f287a416707e61b0936c05ccbe0c64e2cbae1befb47cfe1e18f61da931ca6635cb49200b1ed644d5a70956dde52ad27ed66a3f7db8291

test:
  secret_key_base: cca8f0063b057dda982471c615334a7f7ff83ae1a01a70dc0c46c6c67f285a3411319704382293abb80cae0d1b0db132325948ece11fa888074394564ff59869

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
